[package]
name = "host"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
assigned-reputation-core = { path = "../core/assigned-reputation" }
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
methods = { path = "../methods" }
prior-voting-history-core = { path = "../core/prior-voting-history" }
risc0-zkvm = { version = "=3.0.6", default-features = false, features = ["client", "disable-dev-mode"] }
verifier = { path = "../verifier" }
serde = "1.0"
